[colors.bright]
black = "#4c4c4c"
blue = "#b3deef"
cyan = "#73cef4"
green = "#c9d05c"
magenta = "#d3b987"
red = "#f43753"
white = "#feffff"
yellow = "#ffc24b"

[colors.normal]
black = "#282828"
blue = "#b3deef"
cyan = "#73cef4"
green = "#c9d05c"
magenta = "#d3b987"
red = "#f43753"
white = "#eeeeee"
yellow = "#ffc24b"

[colors.primary]
background = "#282828"
foreground = "#eeeeee"

[env]
TERM = "xterm-256color"

[font]
size = 12.5

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[schemes.hybrid.bright]
black = "#484c52"
blue = "#96b1c9"
cyan = "#9fc9c3"
green = "#dffebe"
magenta = "#bfa5c7"
red = "#d27c7b"
white = "#fcf7e2"
yellow = "#f0d189"

[schemes.hybrid.normal]
black = "#35383b"
blue = "#7693ac"
cyan = "#749e99"
green = "#769972"
magenta = "#977ba0"
red = "#b05655"
white = "#848b92"
yellow = "#e1a574"

[schemes.hybrid.primary]
background = "#27292c"
foreground = "#d0d2d1"

[schemes.tender.bright]
black = "#4c4c4c"
blue = "#b3deef"
cyan = "#73cef4"
green = "#c9d05c"
magenta = "#d3b987"
red = "#f43753"
white = "#feffff"
yellow = "#ffc24b"

[schemes.tender.normal]
black = "#282828"
blue = "#b3deef"
cyan = "#73cef4"
green = "#c9d05c"
magenta = "#d3b987"
red = "#f43753"
white = "#eeeeee"
yellow = "#ffc24b"

[schemes.tender.primary]
background = "#282828"
foreground = "#eeeeee"

[terminal.shell]
program = "/run/current-system/sw/bin/zsh"

[window]
opacity = 0.85

[terminal]
