" Vim

" view
set number
set relativenumber
set cursorline
set nowrap
set colorcolumn=80
set scrolloff=5
set laststatus=2
set pumheight=10
set list
set listchars=tab:^\ ,trail:~
set display=lastline
set completeopt+=preview

" inputs
set spell
set spelllang=en,cjk
set clipboard=unnamed,autoselect
set backspace=indent,eol,start
set encoding=utf-8
set fileencoding=utf-8
set fileformats=unix,dos,mac
set ambiwidth=double

" tab
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set autoindent
set smartindent

" search
set ignorecase
set smartcase
set wrapscan
set incsearch
set hlsearch

" others
set mouse=a
set autoread
set showcmd
set showmatch
set wildmenu
set nobackup
set noswapfile
set history=10000

hi Comment ctermfg=3

" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
" call plug#begin('~/.vim/plugged')
call plug#begin('~/.cache/vim/plugged')

" Make sure you use single quotes
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'mattn/vim-goimports'
Plug 'mattn/emmet-vim'
Plug 'posva/vim-vue'
Plug 'itchyny/lightline.vim'
Plug 'cohama/lexima.vim'
Plug 'morhetz/gruvbox'

Plug 'prettier/vim-prettier', { 'do': 'yarn install' }

" Initialize plugin system
call plug#end()

" vim-lsp
let g:lsp_signs_enabled = 1
let g:lsp_diagnostics_echo_cursor = 1

" asyncomplete
let g:lsp_async_completion = 1
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr>    pumvisible() ? "\<C-y>" : "\<cr>"
imap <c-space> <Plug>(asyncomplete_force_refresh)
autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif

" theme
syntax on
colorscheme gruvbox
set background=dark

hi Normal guibg=NONE ctermbg=NONE

" COMMAND MAPS
inoremap jj <Esc>
tnoremap <silent> <ESC> <C-\><C-n><C-w>
nnoremap <silent><Esc><Esc> :<C-u>set nohlsearch!<CR>
noremap! <C-?> <C-h>

" WINDOW MAPS
nnoremap s <Nop>
nnoremap sj <C-w>j
nnoremap sk <C-w>k
nnoremap sl <C-w>l
nnoremap sh <C-w>h
nnoremap sJ <C-w>J
nnoremap sK <C-w>K
nnoremap sL <C-w>L
nnoremap sH <C-w>H
nnoremap sn gt
nnoremap sp gT
nnoremap sr <C-w>r
nnoremap s= <C-w>=
nnoremap sw <C-w>w
nnoremap so <C-w>_<C-w>|
nnoremap sO <C-w>=
nnoremap sN :<C-u>bn<CR>
nnoremap sP :<C-u>bp<CR>
nnoremap st :<C-u>tabnew<CR>
nnoremap sT :<C-u>Unite tab<CR>
nnoremap ss :<C-u>sp<CR>
nnoremap sv :<C-u>vs<CR>
nnoremap sq :<C-u>q<CR>
nnoremap sQ :<C-u>bd<CR>
