#!/bin/sh

# MOUSE=$(xinput | awk -F'[=]' '/Kensington Expert Wireless TB Mouse/ {print $2}' | awk '{print $1}')
MOUSE=$(xinput | awk -F'[=]' '/Designer Mouse/ {print $2}' | awk '{print $1}')

if [ -z "$MOUSE" ]; then
  echo "mouse is not found."
  exit 1
fi

# xinput set-button-map $MOUSE 1 2 3 4 5 6 7 8 9
xinput set-button-map $MOUSE 3 2 1 4 5 6 7 8 9
